version: "3"

services:
  bet_maker:
    build: .
    container_name: bet_maker
    restart: always
    ports:
      # main
      - 8080:8080
      # debug adapter
      - 5678:5678
    depends_on:
      - postgres
    volumes:
      - ./:/usr/bet_maker

  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
